### ISSUE TITLE
Rename Garbage to GarbageCollector

### ISSUE THREAD

**Issue by TimvdLippe** [txsmith/throwingLambdas#4]
GarbageCollector sounds better, however makes the `using` invocation more verbose:

```Java
using((GarbageCollector collector, Input input) -> {...})
```
But this is a result of the compiler currently not being able to determine the type of `input`. So if we are able to fix that issue, then renaming would sound more logical in my opinion.

**Comment by txsmith** [comment]
I would propose removing the Input argument. If you think of it, it's not a very useful argument to have:

```Java
using((Garbage garbage, InputStream i) -> {
    garbage.add(i, silenceExceptions(AutoCloseable::close));
    // ...
}).with(getResourceAsStream("/someFile"));
```
This method only allows for *one* argument to be passed into the consumer, while the goal of the using()-syntax is to be able to nicely clean up *multiple* things. This does not make sense.

We could rewrite things to:
```Java
using((GarbageCollector collector) -> {
    InputStream i = getResourceAsStream("/someFile");
    collector.add(i, silenceExceptions(AutoCloseable::close));
    // ...
});
```
which is easier to read in my opinion.

**Comment by txsmith** [comment]
We could then also rename ``using()`` to ``autoCleanup()``

**Comment by JeremybellEU** [comment]
I think `autoCleanup()` is the way to go. Also in relation to my comment on #5
