### ISSUE TITLE
Transfer garbage related methods and classes to other container class

### ISSUE THREAD

**Issue by TimvdLippe** [txsmith/throwingLambdas#5]
The garbage related methods are not really related to all other methods defined in `ThrowingLambdas`. We could transfer `using`, `TryFinally`, `Garbage` and `GarbageThrowingConsumer` to a seperated class called `GarbageCollector`.

**Comment by txsmith** [comment]
agreed

**Comment by JeremybellEU** [comment]
I really think the GarbageCollector can be moved to its own library with corresponding interfaces. At least I would use the code. Maybe rename this repo for that and throw out the functional stuff?
